services:
  schulbuddy:
    build: .
    container_name: schulbuddy-app
    ports:
      - "${EXTERNAL_PORT:-5000}:${PORT:-5000}"
    environment:
      - FLASK_ENV=production
      - SECRET_KEY=${SECRET_KEY:-your-production-secret-key-change-this}
      - DATABASE_URL=sqlite:////app/data/schulbuddy.db
      - DOCKER_ENV=1
      - HOST=${HOST:-0.0.0.0}
      - PORT=${PORT:-5000}
      - SESSION_TIMEOUT_MINUTES=120
      - REMEMBER_COOKIE_DAYS=30
      - LOGIN_TIMEOUT_MINUTES=60
      - MAX_LOGIN_ATTEMPTS=5
      - LOGIN_ATTEMPT_TIMEOUT_MINUTES=15
      - CURRENT_SCHOOL_YEAR=2024/25
      - CURRENT_SEMESTER=1
    volumes:
      - ./instance:/app/data
      - ./static/uploads:/app/static/uploads
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${PORT:-5000}/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: nginx reverse proxy
  nginx:
    image: nginx:alpine
    container_name: schulbuddy-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - schulbuddy
    restart: unless-stopped
    profiles:
      - nginx

volumes:
  schulbuddy_data:
    driver: local
  schulbuddy_uploads:
    driver: local

networks:
  default:
    name: schulbuddy-network
