version: '3.8'

services:
  schulbuddy:
    build:
      context: .
      dockerfile: Dockerfile.raspberry-pi
    ports:
      - "5000:5000"
    user: "1000:1000"  # Run as user ID 1000 (typical Pi user)
    volumes:
      - ./instance:/app/instance:rw
      - ./static/uploads:/app/static/uploads:rw
    environment:
      - SECRET_KEY=raspberry-pi-secure-key
      - DATABASE_URL=sqlite:///instance/schulbuddy.db
      - FLASK_ENV=production
      - SESSION_TIMEOUT_MINUTES=120
      - CURRENT_SCHOOL_YEAR=2024/25
      - CURRENT_SEMESTER=1
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

networks:
  default:
    name: schulbuddy-network
